services:
  - type: web
    name: springboot-app
    env: static
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render/opt/openjdk-17
